### ISSUE TITLE
Docker multistage with php-fpm

### ISSUE THREAD

**Issue by frugan-it** [bitnami/bitnami-docker-google-cloud-sdk#2]
Hi, I should integrate the `bitnami/google-cloud-sdk` image inside the `bitnami/php-fpm` image; I need in fact that the commands `gcloud`, `gsutil`, etc. are accessible from PHP.

My approach is as follows:

Dockerfile:
```dockerfile
FROM bitnami/google-cloud-sdk:latest as build

USER 0

#https://stackoverflow.com/a/64557582/3929620
#https://github.com/moby/moby/issues/34645
# This command slows down the building process.. but trust and wait!
RUN chown -Rf root:root \
        /opt/bitnami/google-cloud-sdk \
    ;

USER 1001

FROM bitnami/php-fpm:latest

ENV USER_ID=1000 \
    GROUP_ID=1000

#https://stackoverflow.com/a/51304870/3929620
COPY --from=build /.config /home/daemon/.config
COPY --from=build /opt/bitnami/google-cloud-sdk /opt/bitnami/google-cloud-sdk

RUN install_packages \
        #https://github.com/GoogleCloudPlatform/cloud-sdk-docker/pull/87
        openssh-client \
	python \
    ; \
    # This command slows down the building process.. but trust and wait!
    chown -Rf ${USER_ID}:${GROUP_ID} \
        /home/daemon/.config \
        /opt/bitnami/google-cloud-sdk \
    ;

#https://stackoverflow.com/a/52842111/3929620
ENV PATH /opt/bitnami/google-cloud-sdk/bin:$PATH
```

Even if the resulting image is not very light, the system works in the end.
I just wanted to know if it's the correct approach, or if you can recommend improvements, thanks.

**Comment by Mauraza** [comment]
Hi @frugan-it,

> If I go your own way, I should then update references to required packages, Python version, download links (eg. https://downloads.bitnami.com/...), etc. in the future, or am I wrong?

You are right you will need to update in the future.

> Doesn't it make more sense to call bitnami/google-cloud-sdk:last image, to always be up to date?

Always be up to date is important but before update it is necessary to test that everything is working properly, so if you use an exact version is easy to check the errors produced by the new version of a component.

**Comment by frugan-it** [comment]
Ok thanks, now I understand better the meaning of your approach.. :smile:

**Comment by Mauraza** [comment]
Hi  @frugan-it,

Do you have any other questions?
