### ISSUE TITLE
Debian-11  release? 

### ISSUE THREAD

**Issue by xueshanf** [bitnami/bitnami-docker-google-cloud-sdk#3]
### Name and Version

bitnami / bitnami-docker-google-cloud-sdk:latest

### What is the problem this feature will solve?

Debian-11 based image will allow us to upgrade other application packages to newer release that is only available for Debian-11.

### What is the feature you are proposing to solve the problem?

It would be great to have debian-11 based image.

### What alternatives have you considered?

May consider to build our own image starting  from debian-11 OS base image and add google-cloud-sdk.

**Comment by juan131** [comment]
Hi @xueshanf 

Thanks so much for your suggestion!! Debian11 is something on the roadmap for the whole Bitnami catalog but I'm afraid I can't provide you any ETA at this moment for this to happen.
